# Define model
model: LinearRegression
epochs: 100
train: true
predict: true

# Define directories
data_dir: ../../data
model_dir: ../../saved_models

# Specify where to save the results
hydra:
  run:
    dir: ./results/${model}-${now:%m-%d-%H-%M-%S}
  job:
    chdir: true