name: Build & Deploy app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3